# Generated by Django 5.0.6 on 2024-09-16 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeapp', '0002_alter_recipe_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ('name',)},
        ),
    ]
